<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Todo App</h1>
        <h2>Pending Todos</h2>
        <div>
            <form action="/status" method="POST">
            <?php echo \Todos\ViewHelpers\TodosPageViewHelper::outputPendingTodos($todos) ?>
                <input type="submit" value="Save">
            </form>
        </div>
        <h2>Completed Todos</h2>
        <?php echo \Todos\ViewHelpers\TodosPageViewHelper::outputCompletedTodos($completed) ?>
        <br><br>
        <a href="/">Back to Homepage</a>
    </body>
</html>
